%Plot the a 2-D field given by an anonymous function over a specific interval
%function hw3_funGradField(gradf,maxZ)
%Input arguments
%   gradf   Function handle of a function that maps a [2 x 1] vector to
%           another [2 x 1] vector.
%   maxZ    Maximum absolute value of the values generated by gradf. Any
%           element of the vector generated by gradf with absolute value
%           larger than maxZ will be truncated before visualization.
%Output
%   This function evaluates gradf over the points of a regular grid covering the
%   square [-2,2] x [-2,2] and then plots the results using the quiver
%   function. In general, the function gradf will be an anonymous function (see
%   MATLAB documentation on function handles and anonymous functions and
%   the example below).
%Example of use
%   gradf=@(x) diag([1 2])*x+[3;1];
%   hw3_funGradField(gradf,10)
%   axis equal
function hw3_funGradField(gradf,maxZ)
xx=linspace(-2,2,21);
yy=linspace(-2,2,21);
[X,Y]=meshgrid(xx,yy);
Z=zeros([size(X) 2]);
for iX=1:size(X,1)
    for iY=1:size(X,2)
        Z(iX,iY,:)=gradf([X(iX,iY);Y(iX,iY)]);
    end
end
Z=max(min(Z,maxZ),-maxZ);
quiver(X,Y,Z(:,:,1),Z(:,:,2))
