function [val] = wavefront_propogate(val)
    %Uses a 4 connected neighborhood to do wavefront propogation on the
    %already-initialized array val. 
    %   Val is an NxN matrix as generated by wave_front initialize.
    
	set(0,'RecursionLimit',50000);
    [i j] = find(val == 0);
	
    %Declare temporary global variable for all the recursive functions
    global VAL
    VAL = val;
    %Call the recursive propagator
    fan2(i,j,0);
  	val = VAL;
    %Remove the global variable VAL.
    clear VAL;
end
